### PR TITLE
fix: aside bar collapse all the way

### LINKED ISSUE #97: Fix aside collapse

### PR DESCRIPTION
**Pull request by DanielPasion**
fixes #97

### CODE REVIEW

File: addon/components/aside.ts [hunk 1]
```diff
@@ -16,7 +19,13 @@ export interface AsideSignature {
 }
 
 export default class Aside extends Component<AsideSignature> {
-  @tracked isCollapsed = false;
+  // @tracked isCollapsed = false;
```
Comment (charlesfries) [inline addon/components/aside.ts:22]: Delete

File: addon/components/aside.ts [hunk 2]
```diff
@@ -16,7 +19,13 @@ export interface AsideSignature {
...
+  // @action setTrue() {
```
Comment (charlesfries) [inline addon/components/aside.ts:23]: Delete or move this to controller if you're seeing glint errors

**Review by charlesfries — APPROVED** [review]
